### ISSUE TITLE
Wit does not learn 

### ISSUE THREAD

**Issue by tommasnik** [wit-ai/wit#1026]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Wit does not learn at all

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create app - language czech. Train sentence "Ahoj" (czech translation of "hi") and train it as intent "ahoj". Then even if you wait the exact same sentence "Ahoj" is not recognized.
![image](https://user-images.githubusercontent.com/4234245/38042816-a8894a7a-32b5-11e8-8b06-583b5e6102a1.png)

Also we tried to import existing (working) app and it did not work either. App id: 
5abbbccc-11cb-4916-a5b5-7845d4ecdd64

**What is the expected behavior?**
We expect to be close to 100% sure that it's the trained intent. 

**What is the App ID where you are experiencing this issue (if applicable)?**
5abbc165-1531-4152-9ef4-21302413809c

**Comment by l5t** [comment]
We have a backlog in our training queue but we are working on it, it should be fixed soon

**Comment by tommasnik** [comment]
Is there any API for getting status of training? It's not for the first time we experienced such issue and it would be very helpful for us as well as for our users.

**Comment by l5t** [comment]
Thanks for the feedback, we have the training status api on our roadmap and hope to get at it in the next few months

**Comment by tommasnik** [comment]
The app 5abbbccc-11cb-4916-a5b5-7845d4ecdd64 still does not work. It does not recognize any messages even the exact copies of the training data.
Is there still the same problem? Is there any explanation that we as developers could tell to our boss?

**Comment by ondrejbudai** [comment]
I can confirm there's still problem with learning. My newly created apps (20 minutes ago) are still unable to learn anything.

Affected apps' IDs:
```
5abc9699-81cd-434d-a87d-82f667488f06
5abc93ac-42dd-4e06-a0a8-37121ae1cab5
```

**Comment by ondrejbudai** [comment]
Ok, now it works, but the training took quite some time. Surely more than it's indicated by training status icon.

**Comment by l5t** [comment]
Yes the training status is misleading.

**Comment by tommasnik** [comment]
Is it possible that our app 5abbbccc-11cb-4916-a5b5-7845d4ecdd64 is still in training? Can I do anything to make it work?

**Comment by blandinw** [comment]
We fixed training issues this morning again and are working to prevent them from happening.
