### ISSUE TITLE
Speech API - Internal Server Error

### ISSUE THREAD

**Issue by DiegoHSeto** [wit-ai/wit#2150]
Hi there,

I'm receiving interval server error (500) when calling speech api endpoint with WAV files. I was working with wit app for many days with this audio type and get and i didn't get any error. I'm using the "api.wit.ai/speech" with the latest version.

Has there been any change in the api version?

Regards,

Diego Hiroshi Seto

**Comment by patapizza** [comment]
Hi @DiegoHSeto,

We're currently working on the endpoint.
We're aware of the issue and are actively working on a fix. In the meantime, passing the audio as 16k sample rate, encoded on signed integer 16 bits with little endianness should prevent the issue and speed up the processing time.

Thanks for your patience.

**Comment by patapizza** [comment]
Update: the fix is upcoming. Should be resolved in a couple of hours.

**Comment by DiegoHSeto** [comment]
Hello @patapizza . Thank you for the quick response and your great job :)

Waiting here for the fix.

**Comment by patapizza** [comment]
Fix is deployed, and initial testing looks good. Can you confirm on your end?
I do see some instabilities that I'll have to look more into tomorrow.

**Comment by grigoriy-a** [comment]
Hi guys,
Is this the same issue as constant error 408 on the /speech endpoint?
Regardless of actual file length the server returns 
{
  code: 'audio-too-long',
  error: 'Exceeded max audio length of 20 seconds.'
}

**Comment by rfmeloneto** [comment]
Hi, the same problem is happening to me, but in my case im using the speech recognition lib to acess the Wit Api. 
So, when i try to acess i recive the error : 
recognition request failed: Internal Server Error 
HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error 

I just run the code, and the error remains.

Thank you!

ps. my code was working just fine.

**Comment by DiegoHSeto** [comment]
> Fix is deployed, and initial testing looks good. Can you confirm on your end?
> I do see some instabilities that I'll have to look more into tomorrow.

I keep getting the same error :(. I'm passing the audio as PCM 32-bit floating-point little-endian with 8k of sample rate.

**Comment by patapizza** [comment]
Looking more into it today. In the meantime, sending 16-bit signed-integer little-endian with 16k of sample rate would work (and speed up the processing); 8k sample rate works too.

**Comment by DiegoHSeto** [comment]
> Looking more into it today. In the meantime, sending 16-bit signed-integer little-endian with 16k of sample rate would work (and speed up the processing); 8k sample rate works too.

Sure, while the problem is being fixed i can convert my audio files to this format. If you can keep me up to date about the fix would be great. Thanks again :)

**Comment by patapizza** [comment]
What is your app id?

**Comment by patapizza** [comment]
I'm seeing some underlying infra issues; working with partners to understand how to remedy. I probably won't be able to come up with a fix before tomorrow.
To clarify, the audio conversion on your end wouldn't just resolve the issue - it would make the processing faster. I'll update the HTTP API Reference to reflect that.

**Comment by DiegoHSeto** [comment]
App Id: 2621810151445138

Cool, if you can solve this issue with your partners i would appreciate it haha, the conversion would make the processing more faster but i have a cost here. Anyway i can fix my end with this additional process while you work on this.

**Comment by patapizza** [comment]
This should be now resolved. Let me know if you still experience issues.
