### ISSUE TITLE
Error: Something went wrong. We've been notified #2623

### ISSUE THREAD

**Issue by Cameronk0007** [wit-ai/wit#2642]
Do you want to request a feature, report a bug, or ask a question about wit?
Report a bug
What is the current behavior?
utterances - Error: Something went wrong. We've been notified which is breaking NLP on my facebook chat bot
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
Utterance API Should not break,
image

What is the expected behavior?
Return utterances
If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.
https://wit.ai/apps/1454843927927779/utterances App ID is 1454843927927779

**Comment by maidaneze** [comment]
Could you try again? It should be fixed by now.

**Comment by Cameronk0007** [comment]
Hi there. It still seems to be broken :(

**Comment by maidaneze** [comment]
We are looking into it. Will come back once we get more information.

**Comment by ChrisyShine** [comment]
The utterances page: https://wit.ai/apps/1454843927927779/utterances should be accessible now.

**Comment by Cameronk0007** [comment]
Hello.

Thank you so much.

The utterance api is now working fine on wit.ai and the export
functionality now works too.

However on Facebook I am still getting the same error for the NLP.

**Comment by ChrisyShine** [comment]
Can you share an utterance you used with the chatbot? And have you tried the /message API, does it work?

**Comment by Cameronk0007** [comment]
That was the utterance used. I have not seen message api to test that. How
do I navigate to msg api?

**Comment by Cameronk0007** [comment]
Hi there, any feedback on this?

**Comment by ChrisyShine** [comment]
If /message API works well, the wit.ai configuration should be good. Can you double check if the Chatbot webhook setting is good?

**Comment by Cameronk0007** [comment]
Okay I will double check the we book.


Another thing to note. We are using the wit.ai access token on 2 different
chat bots.

The stagging one and the live one.

Currently the stagging one still works fine. It’s just the live one that
seems to be an issue.

Is it possible that it is not working because we are using the same one on
stagging?

If is there something else I should look into?

When you speak about the web hook. You mean the one on Facebook for
developers where we insert the access token?

Kind regards
Cameron

**Comment by maidaneze** [comment]
We will close this task for now. Please open it again if the issue persists.

**Comment by Cameronk0007** [comment]
Hi Team, It seemed to be working nicely just before u closed this ticket
for a while, now i see it is broken again, can you please advise why this
is happening?

Please see screen shot below.

[image: image.png]
