### ISSUE TITLE
Ongoing training status

### ISSUE THREAD

**Issue by kl-wong** [wit-ai/wit#747]
I have created a function to randomly pick expression and entity from JSON file to train the APP. Since I started doing that, the training status never go "Clean". I probably loaded in about 2000 expressions. 

Is there anything wrong with the APP?

App ID
59a498fb-c649-471f-89b4-2b64a0658dff

**Comment by kl-wong** [comment]
In addition, most of the entity doesn't have the insight chart showing even though there are more than 50 expressions.

**Comment by l5t** [comment]
Can you share your Wit app URL?

**Comment by patapizza** [comment]
Hi @kl-wong,

I've fixed the training for your app. I'll look into why Insights don't show up.

**Comment by kl-wong** [comment]
Thanks Laurent.

Here is the URL https://wit.ai/kinlokwong/QuoteMe/

On 30 Aug. 2017 01:11, "Laurent Landowski" <notifications@github.com> wrote:

Can you share your Wit app URL?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wit-ai/wit/issues/747#issuecomment-325695471>, or mute
the thread

**Comment by patapizza** [comment]
@kl-wong: I'm able to see the Insights for your entities now.

**Comment by kl-wong** [comment]
3 out of 4 user-defined entity have the insights but the one prefix still doesn't show.

**Comment by patapizza** [comment]
`prefix` has a keywords search strategy, which doesn't provide Insights.

**Comment by kl-wong** [comment]
Thanks for clarifying that.

**Comment by zhanpengli** [comment]
hi,i also have the same problem with my wit.ai,can u help me?? thanks very much!!
my wit url is : https://wit.ai/zhanpengli/AfterSale_v1/entities

**Comment by l5t** [comment]
I just restarted you training. It should turn green soon

**Comment by zhanpengli** [comment]
ok,thanks~~
